# docker run --name node-exporter -d -p 9100:9100 prom/node-exporter:v1.3.1
# grafana theme：11074
version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: node-exporter
    image: sharkgulf/node-exporter-tunnel:1.0.1
    # ports:
    #  - "9100:9100"
    environment:
      TUNNEL_SERVER: 192.168.0.52:9312
      TUNNEL_FORWARD: 11199
      TUNNEL_PWD: xxx
    restart: unless-stopped